### ISSUE TITLE
Filter Date Range SQL format

### ISSUE THREAD

**Issue by sfblaauw** [lexik/LexikFormFilterBundle#103]
Hi, one question. 
I'm using the `filter_date_range` and I saw in the method `convertToSqlDate` in class `ExpressionBuilder` that converts the left date to 1970-01-01 00:00:00 and the right date to 2014-06-01 23:59:59, that is cool form me, but after the date formats to 'Y-m-d'.
I know that is the `filter_date_range` not the `filter_datetime_range` but I thing it will be nice to use the sql date time format 'Y-m-d H:i:s' in this tipe of filter. 
Thanks

**Comment by xawiers** [comment]
+1 UP
