### ISSUE TITLE
No value found for key "left_datetime" in form data.

### ISSUE THREAD

**Issue by Rvanlaak** [lexik/LexikFormFilterBundle#139]
When we submit a `filter_datetime_range` where the time is not filled in, the FilterForm obviously throws an error.

    No value found for key "left_datetime" in form data.

We tried to make use of `$form->handleRequest()` to let the validator check the fields, but it seems the FilterForms don't support it.

    Warning: array_merge(): Argument #1 is not an array
    in vendor/lexik/form-filter-bundle/Lexik/Bundle/FormFilterBundle/Filter/DataExtractor/Method/ValueKeysExtractionMethod.php at line 33 

It seems the fields with a left and right side need their own `DataExtractionMethodInterface`.

How can I add validators to the forms? I'd like to use the regular flow of the Symfony Form component if this is possible. Any reasons why `handleRequest` is not supported?

**Comment by cedric-g** [comment]
Hi, I don't know if it's your case or not, but this error can occur if you display the date/datatime field as a `single_text` widget, in this case you have to set the `format` option too.

**Comment by Rvanlaak** [comment]
Yes you are correct about that, my field is formatted as html5 single text.

**Comment by bkosborne** [comment]
I am running into this problem as well, but I'm not using anything other than the default. When I have nothing submitted to the filter form, I get this warning:

> Warning: array_merge() [<a href='function.array-merge'>function.array-merge</a>]: Argument #1 is not an array in /Users/bkosborne/Sites/ADM/vendor/lexik/form-filter-bundle/Lexik/Bundle/FormFilterBundle/Filter/DataExtractor/Method/ValueKeysExtractionMethod.php line 33

Here's some relevant snippets of my form builder and controller:

Form builder:
```
            ->add('date', 'filter_date_range', array(
                'left_date_options' => array(
                    'label' => 'Min',
                ),
                'right_date_options' => array(
                    'label' => 'Max',
                ),
            ))
```

Controller:
```
        $qb = $this->getDoctrine()->getManager()->createQueryBuilder();
        $qb
            ->select('Degree')
            ->from('AppBundle\Entity\Degree', 'Degree')
        ;

        // Setup the filter form
        $filterForm = $this->createForm('degree_filter', null, array(
            'action' => $this->generateUrl('degree'),
            'method' => 'GET',
        ));
        $filterForm->add('submit', 'submit', array('label' => 'Filter'));
        $filterForm->handleRequest($request);

        // Apply the filters to the query
        $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($filterForm, $qb);

        // Apply pagination
        $maxItemPerPage = $request->query->get('maxItemPerPage');
        if (!$maxItemPerPage) {
            $maxItemPerPage = 25;
        }
        $paginator = $this->get('knp_paginator');
        $paginatedDegrees = $paginator->paginate(
            $qb->getQuery(),
            $this->get('request')->query->get('page', 1),
            $maxItemPerPage,
            array('defaultSortFieldName' => 'Degree.conferredDate', 'defaultSortDirection' => 'DESC')
        );
        $paginatedDegrees->setPageRange(5);

        return $this->render('AppBundle:Degree:index.html.twig', array(
            'filter_form' => $filterForm->createView(),
            'degrees' => $paginatedDegrees,
        ));
```

**Comment by bkosborne** [comment]
Here's a patch: https://github.com/lexik/LexikFormFilterBundle/pull/145

**Comment by bkosborne** [comment]
Disregard the path above, I wasn't looking at the code in master. This PR actually resolves my issues: https://github.com/lexik/LexikFormFilterBundle/pull/140

I just needed to use an `isValid()` method call before adding filter condition:

```php
        if ($filterForm->isValid()) {
            // Apply the filters to the query
            $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($filterForm, $qb);
        }
```
