### ISSUE TITLE
Unable to pass own QueryBuilder

### ISSUE THREAD

**Issue by rvanlaak** [lexik/LexikFormFilterBundle#141]
The behaviour as described on [UPGRADE3.0.md](https://github.com/lexik/LexikFormFilterBundle/blob/master/UPGRADE-3.0.md) does not allow me to inject my own pre-populated QueryBuilder anymore.

Returning the condition instead of directly adding the condition in `apply_filter` is fine, but i think it should use the QueryBuilder to add it to as long as possible, instead of going to a [newly created `ORMQuery` or `DBALQuery`](https://github.com/lexik/LexikFormFilterBundle/blob/69b6dbedf80c01fd863b209d5a0fa35a85669749/Event/Listener/PrepareListener.php#L61-L84)

Another related point, how can I add a join condition and a where condition, or multiple where conditions? Shouldn't it be better if the `apply_filter` callable always returns [a Traversable object](http://php.net/manual/en/class.traversable.php)?

**Comment by cedric-g** [comment]
Hi, on the `QueryInterface` object you can still call the `getQueryBuilder()` method and add some joins on the query builder if you need it. 

About the multiple where conditions, you an prepare a `andX` or `orX` expression:

```php
$expression = $filterQuery->getExpr()->andX(
    'field_a = :param_a',
    'field_b = :param_b'
);

$parameters = array(...);

$filterQuery->createCondition($expression, $parameters);
```

**Comment by Rvanlaak** [comment]
> Hi, on the QueryInterface object you can still call the getQueryBuilder() method and add some joins on the query builder if you need it.

By allowing this you still can let users ignore the new way of adding conditions by letting the callable return it. I think returning conditions (or adding them directly) should be the only way :)

The current order is:
1. `$em->getRepository()->createQueryBuilder()` // This filterBuilder already has all neccesary joins
2. Create FilterForm (based on Entity type)
3. `$this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($filterForm, $filterBuilder);`
But if I understand you correctly, this means I should ad my own expressions after `addFilterConditions` right?


When I dig into the code, the `PrepareListener::onFilterBuilderPrepare` seems to inject the `$qb` into the `DBALQuery`. But in the end it doesn't seem to preserve all previous conditions.

**Comment by cedric-g** [comment]
The `DBALQuery` and `ORMQuery` classes are just some wrapper classes, it doesn't change anything in the doctrine query builder. 

If you want to keep previously added conditions, just use the `where_method` config option :)
See [Query builder method](https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/configuration.md#bundles-options) section.

I compute the global condition (I mean the aggregation of each field's condition) in [DoctrineApplyFilterListener](https://github.com/lexik/LexikFormFilterBundle/blob/master/Event/Listener/DoctrineApplyFilterListener.php#L35) and by default I use the `where()` method to add it, so it override the where clause.

**Comment by Rvanlaak** [comment]
> So it will override the existing where clause.

Interesting documentation about the QueryBuilder method. Won't changing this to `or` mean that the between-range filters will result into weird behaviour? Something like `price > 10 OR price < 10`. Or will the range filters keep use `AND`?

**Comment by cedric-g** [comment]
This option won't affect operators you defined with the `filter_condition_builder` option in your form type.

Let's say we prepared a query builder with `default_field = :param_default` and we have a form type with 2 fields linked with a `AND` operator so the entire filter condition will be `field_a = :param_a AND fieldb = :param_b`.

If you use:
* `where_method: ~` you will loose  `default_field = :param_default` as the `DoctrineApplyFilterListener` will add the filter condition by calling `$queryBuidler->where('field_a = :param_a AND fieldb = :param_b')`

* `where_method: and` the `DoctrineApplyFilterListener` will add the filter condition by calling `$queryBuidler->andWhere('field_a = :param_a AND fieldb = :param_b')`

* `where_method: or` the `DoctrineApplyFilterListener` will add the filter condition by calling `$queryBuidler->orWhere('field_a = :param_a AND fieldb = :param_b')`

**Comment by Rvanlaak** [comment]
Thanks! Did figure it out exactly as you mention here. The default use case is to inject a new `QueryBuilder` right? Should there be any reason to overwrite the existing where statements? To me it looks like `andWhere` should be the default behaviour.

**Comment by cedric-g** [comment]
Yes the default case is to inject a query builder without any conditions as it will be computed by the bundle, that's why by default I call `->where()`. But changing the default behaviour to `andWhere()` is probably more intuitive than overriding the where clause.

**Comment by Rvanlaak** [comment]
Changing the default behaviour would be nice. Maybe also log a warning when the passed `QueryBuilder` already has conditions:

```php
if (count($queryBuilder->getQueryParts()) {
   $logger->warning('The QueryBuilder already has conditions, which will be overridden');
}
```

**Comment by alamirault** [comment]
I think replace `where` by `andWhere` is the best solution. I can make a PR if you wants but is this project still maintained ?
