### ISSUE TITLE
Unmapped fields are throwing errors

### ISSUE THREAD

**Issue by mbates** [lexik/LexikFormFilterBundle#142]
I have a couple of fields in my FitlerFormType that are used for calculations, and do not map to anything. I've tried setting mapped => false but I get an error when I submit my form.

For Example, in my FilterType I have

    ->add('late_days', 'choice', array(
        'label' => 'forms.surgeries.required_delivery_days',
        'placeholder' => 'forms.surgeries.select_required_days',
        'choices' => array(
            '1' => '1',
            '2' => '2',
            '3' => '3',
            '4' => '4',
            '5' => '5'
        ),
        'mapped' => false,
        'data' => '1',
    ))

In my controller when I get to this line

    $filterForm->submit($request->request->get($filterForm->getName()));

An exception is thrown

    [Semantical Error] line 0, col 156 near 'late_days = :s_late_days': Error: Class Incompass\SurgeryBundle\Entity\Surgery has no field or association named late_days

At the moment I'm having to do this as a workaround

    if ($requestValues = $request->request->get($filterForm->getName())) {
        // Extract Late Days from Filters
        $lateDays = $requestValues['late_days'];
        unset($requestValues['late_days']);
        $request->request->set($filterForm->getName(), $requestValues);

        $filterForm->submit($request->request->get($filterForm->getName()));

But that's not so great as the filters field is now blank on the page, and I would have to set it again using jQuery or something.

**Comment by cedric-g** [comment]
Hi, the fact is by default the bundle will add some condition for all form types (even for SF2 form types as `choice`). 
Maybe I should add an option to enable/disable listener on default SF2 form types or to disable a filter.
But if you use the 3.x version, a quick fix for you would be to define the `appy_filter` option on `late_days` and don't do anythnig in the closure:

```
use Lexik\Bundle\FormFilterBundle\Filter\Query\QueryInterface;

// ...

->add('late_days', 'choice', array(
    // ...
   'appy_filter' => function (QueryInterface $filterQuery, $field, $values) {
        return null;
   }
))
```

**Comment by cedric-g** [comment]
I've updated the master branch, now you can disable a filter by setting `apply_filter` to false.
```
->add('late_days', 'choice', array(
    // ...
   'appy_filter' => false,
))
```

**Comment by Rvanlaak** [comment]
Shouldn't it just follow the `mapped` parameter?

**Comment by mbates** [comment]
Thanks,

Personally I like the 'apply_filter' option over the 'mapped', as that is more semantically correct for filter forms. For normal forms 'mapped' would be better.

I'll get this change tested out this week so this can be closed.

**Comment by cedric-g** [comment]
@Rvanlaak if it follow the `mapped` option, the following use case would not be possible:

Let's say you need a single "search" field that add a condition on several properties "name" and "email"

```php
->add('search', 'filter_text', array(
    // ...
   'mapped' => false,
   'apply_filter' => function (QueryInterface $filterQuery, $field, $values) {
        if (empty($values['value']) {
            return null;
        }

        $expression = $filterQuery->getExpr()->orX(
            $filterQuery->getExpr()->eq('name', ':search'),
            $filterQuery->getExpr()->eq('email', ':search')
        );

        $parameters = array('search' => $values['value']); 

        return $filterQuery->createCondition($expression, $parameters);
   }
))
```
