### ISSUE TITLE
Can't use Composer with SF 2.6

### ISSUE THREAD

**Issue by byhoratiss** [lexik/LexikFormFilterBundle#143]
Hi, I used this bundle into an old project using sf2.1 and works really well.

Now I want to use it into a sf2.6 project by doing:
```
composer require "lexik/form-filter-bundle": "3.*@dev"
```

But I'm getting:
```
  [InvalidArgumentException]                                                                                                               
  Could not find package 3.*@dev at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

I tried even the 3.0.4 tag, lowering the minimum stability to "dev" (bad idea), without success, any idea how to solve this?

**Comment by cedric-g** [comment]
Hi, maybe you can try (in your composer.json):
```json
    "minimum-stability": "dev",
    "prefer-stable": true,
```

**Comment by byhoratiss** [comment]
Yes, I also tried that one (as I said).

I made it work without requiring it from command line, and adding it right into the composer.json and doing a "composer update lexik/form-filter-bundle".
