### ISSUE TITLE
Too few parameters using filter_entity with knp_paginator

### ISSUE THREAD

**Issue by webdevilopers** [lexik/LexikFormFilterBundle#144]
I coupled this bundle to the `knp_paginator`. I added a `fitler_entity` and then passed the `query` as described in the docs:
https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/working-with-the-bundle.md#i-simple-example

```php
$query = $filterBuilder->getDql();
```

This will throw: **Too few parameters: the query defines 1 parameters but you only bound 0**.

As @cedric-g correctly stated in https://github.com/lexik/LexikFormFilterBundle/issues/89 the `getDql()` method only returns the DQL string without the parameters.

Instead I had to use:
```php
$query = $filterBuilder->getQuery();
```

Maybe we could add an example to the docs?

**Comment by cedric-g** [comment]
Hi, the aim of the documentation section you mentioned is just to show the doctrine query builder and so the DQL has been updated according to the filters defined in the form type. So yes if you use KnpPaginator or Pagerfanta you will have to use `getQuery()` as these 2 paginators expect a query object.

And yes maybe we can add a specific section about KnpPaginator / Pagerfanta.

**Comment by webdevilopers** [comment]
Created PR. Closing.
