### ISSUE TITLE
filter_entity doubt

### ISSUE THREAD

**Issue by rafaeldex** [lexik/LexikFormFilterBundle#148]
I have an entity named Product with just one field: name. And i have other entity named Sale with fields: date, product, quantity and price.

I created a filter form to filter entity Sale and i use filter_entity in product field.

->add('product', 'filter_entity', array(
'class' => 'MyBundle:Product',
'property' => 'name',
)

it filters all ok but i cant use field product from Sale in template.

I get error:

Key "product" for array with keys "id, quantity, price" does not exist in MyBundle: Sale:filter.html.twig at line 187.

Any help?
Sorry but i am new using symfony and this bundle.

**Comment by cedric-g** [comment]
Hi, I think you just need to add a join to your doctrine query builder and add the joined table in the select.

Here I suppose I'm in the SaleRepositoty class:
```php
/**
 * @return \Doctrine\ORM\QueryBuilder
 */
public function initializeFilterQueryBuilder()
{
    return $this
        ->createQueryBuilder('s')
        ->select('s, p')  // select Sale + linked Product, by default only Sale is selected, and so Doctrine hydrate only Sale objects.
        ->leftJoin('s.product', 'p')
}
```

**Comment by rafaeldex** [comment]
Very Good! it worked! Thank you so much.

But now if i have two filter_entity in Sale? (Product and Kind) ? How do i proceed ?

**Comment by rafaeldex** [comment]
ohhh ok.. i got it!

/**
 * @return \Doctrine\ORM\QueryBuilder
 */
public function initializeFilterQueryBuilder()
{
    return $this
        ->createQueryBuilder('s')
        ->select('s, p, k')  // select Sale + linked Product, by default only Sale is selected, and so Doctrine hydrate only Sale objects.
        ->leftJoin('s.product', 'p')
        ->leftJoin('s.kind', 'k')
}
