### ISSUE TITLE
Invalid service definition [symfony 2.6.x]

### ISSUE THREAD

**Issue by MichaelMackus** [lexik/LexikFormFilterBundle#149]
Any ideas? Not sure why these lines are here since there are no corresponding classes:

https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/config/form.xml#L31-L37

Passes fine when I remove those service definitions.

```
InvalidServiceDefinitionsException in ValidateServiceDefinitionsPass.php line 44: Service definition validation errors (2):
- lexik_form_filter.type.filter_field: Class "Lexik\Bundle\FormFilterBundle\Filter\Form\Type\FieldFilterType" does not exist
- lexik_form_filter.type.filter: Class "Lexik\Bundle\FormFilterBundle\Filter\Form\Type\FilterType" does not exist
```

**Comment by Rvanlaak** [comment]
:+1: removing seems legit to me

**Comment by cedric-g** [comment]
It seems legit to me too :smiley_cat: it's an oversight, I just removed these lines.

**Comment by MichaelMackus** [comment]
Thanks!
