### ISSUE TITLE
please tag package even lowest number but a version is needed

### ISSUE THREAD

**Issue by cordoval** [lexik/LexikFormFilterBundle#154]

**Comment by Rvanlaak** [comment]
https://github.com/lexik/LexikFormFilterBundle/releases ?

**Comment by cordoval** [comment]
last one was on 2014, there are several fixes untagged up to date

**Comment by Rvanlaak** [comment]
You're right :+1:

**Comment by garak** [comment]
:+1:

**Comment by cordoval** [comment]
@cedric-g what is left to get to 3.0.5? :+1: good job man and thanks for your work!

**Comment by cedric-g** [comment]
Done :)

**Comment by spike31** [comment]
Good job !

**Comment by cordoval** [comment]
indeed thanks
