### ISSUE TITLE
QueryInterface is missing getAlias() method

### ISSUE THREAD

**Issue by garak** [lexik/LexikFormFilterBundle#155]
I'm not sure if open a PR (it would be easy), so I'm asking before: is there any reason for which ``QueryInterface`` is missing ``getAlias()`` method? Both ``ORMQuery`` and ``DBALQuery`` have that method.

I'd like to use ``getAlias`` inside the Closure of ``apply_filter``, but I'm reluctant, just because the method is not in the interface.

**Comment by cedric-g** [comment]
Hi, yes we can add `getAlias()` in the interface but maybe it should be renamed to `getRootAlias()`. The value returned by this method can be different from `$values['alias']` if you're manipulating embedded filter.

**Comment by garak** [comment]
Great, so I'll work on a PR. Thank you.
