### ISSUE TITLE
How to avoid clashing aliases

### ISSUE THREAD

**Issue by garak** [lexik/LexikFormFilterBundle#156]
Often I need to apply a ``leftJoin`` to Query Builder inside ``apply_filter`` Closure. But there is a chance that I use an alias that was already defined in the same Query Builder instance. So I end up with a Doctrine exception saying something like "Error: 'g' is already defined" (where 'g' is my alias).
Googling, I found this solution on [stackoverflow](http://stackoverflow.com/q/18052789/369194):
```
$joinDqlParts = $queryBuilder->getDQLParts()['join'];
$aliasAlreadyExists = false;

/* @var $join Query\Expr\Join */
foreach ($joinDqlParts as $joins) {
    foreach ($joins as $join) {
        if ($join->getAlias() === '_user') {
            $aliasAlreadyExists = true;
            break 2;
        }
    }
}

if ($aliasAlreadyExists === false) {
    $queryBuilder->innerJoin('parenttable._user', '_user')

}
```

Since this is pretty long, it could be nice to get it somewhere inside ``ORMQuery`` class.
What do you think?

**Comment by Rvanlaak** [comment]
Found myself solving the same problem. I've solved it the same way as you did.

You can get the joins directly with:

    ->getDQLPart('join');

Could be solved in `ORMQuery` in my opinion :+1:

**Comment by cedric-g** [comment]
Hi, yes we can add a method to check if a given alias exists or not in `QueryInterface`.

**Comment by spackmat** [comment]
Hi, just a question to besser understand you: Why did you implement `hasJoinAlias()` in the ORMQuery class? I need to check, if a Join is already there from inside an `add_shared` closure, where I only have access to a `QueryBuilder` instance, so I must do the full check there. (Thanks by the way for your solution). Or did I miss something? My code now looks like this:

    'add_shared' => function (FilterBuilderExecuterInterface $qbe) {
        $closure = function(QueryBuilder $filterBuilder, $alias, $joinAlias, Expr $expr) {
            $joinParts = $filterBuilder->getDQLPart('join');
            $hasJoin = false;
            foreach ($joinParts as $rootAlias => $joins) {
                foreach ($joins as $join) {
                    if ($join->getAlias() === $joinAlias) {
                        $hasJoin = true;
                    }
                }
            }
            if (false === $hasJoin) {
                $filterBuilder->leftJoin($alias . '.myJoinTable', $joinAlias);
            }
        };
        $qbe->addOnce($qbe->getAlias() . '.myJoinTable', 'myJoinTable', $closure);
    }

**Comment by cedric-g** [comment]
Hi, I've added it in the `Query` classes because these classes aim to group all data you may need during the different steps of the process.
In theory by using `$qbe->addOnce()` the join should be added only once because if the join "definition" `$qbe->getAlias() . '.myJoinTable', 'myJoinTable'` has already been added the `$closure` won't be executed.
But I admit it would be relevant to able to use `hasJoinAlias()` in the `add_shared` option as it aim to deal with the query builder relations. The `FilterBuilderExecuter` class has the `Query` object as property so we can easily add a getter or a proxy method to call `hasJoinAlias()`.

**Comment by spackmat** [comment]
Hi, the addOnce()-Method sounded like it would add the join only, if it is not already joined. But it doesn't. I digged a bit into it:

    if (isset($this->parts[$join])) {
        return null;
    }

This should do the trick, but in my case, `$this->parts` only contained one element: `array:1 ["p" => "__root__"]`, so this check doesn't find the already joined joins an I get the "Error: 'myJoinTable' is already defined." message.

**Comment by cedric-g** [comment]
@spackmat can you have a try with the branch `improve_parts`, I've changed the way to manage parts (by using an object instead of an array by reference), I've also added a `getFilterQuery()` method on the `FilterBuilderExecuter` class.

```php
'add_shared' => function (FilterBuilderExecuterInterface $qbe) {

    $closure = function(QueryBuilder $filterBuilder, $alias, $joinAlias, Expr $expr) use ($qbe) {
        if (false === $qbe->getFilterQuery()->hasJoinAlias($joinAlias)) {
            $filterBuilder->leftJoin($alias . '.myJoinTable', $joinAlias);
        }
    };

    $qbe->addOnce($qbe->getAlias() . '.myJoinTable', 'myJoinTable', $closure);
}
```

**Comment by spackmat** [comment]
@cedric-g Of course. :)

I can confirm, this works as expcted in my case. Nice and thank you for caring!

**Comment by spackmat** [comment]
I saw this is part of the 4.0.2 release, works for me now. Perfect!
