### ISSUE TITLE
Filter Type Relations

### ISSUE THREAD

**Issue by Timo-Linde** [lexik/LexikFormFilterBundle#159]
I followed the instructions on https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/working-with-the-bundle.md#b-single-object
for One to one Relations.

My Model is:
Order -> oneToOne -> Customer -> oneToOne -> Address

I want to filter Orders with the firstname attribute from Address.

I have a OderIndexViewFilterType:

    <?php
    /* 
     *  © 2015 Fitness Megastore All Rights Reserved
     */
    
    namespace FMS\System\MainBundle\Filter;
    
    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Symfony\Component\OptionsResolver\OptionsResolverInterface;
    use FMS\System\MainBundle\Filter\ApplyFilters;
    use FMS\System\MainBundle\Entity\Order;
    use FMS\System\MainBundle\Filter\OrderCustomerFilterType;
    
    class OrderIndexViewFilterType extends AbstractType
    {
        public function buildForm(FormBuilderInterface $builder, array $options) { 
            
            $builder->add('status', 'filter_choice', array(
                'choices' => array(Order::orderOpen => "offen", Order::orderPrinted => "gedruckt",
                    Order::cancellationOpen => "offene Stornierung", Order::cancellationPrinted => "gedruckte Stornierung")
            ));
            $builder->add('invoiceId', 'filter_number');
    
            $builder->add('Customer', new OrderCustomerFilterType(), array(
                'add_shared' => OrderCustomerFilterType::getAddShared()
                )
            );
            
            $builder->add('sales', 'filter_number');
            
            $builder->add('createDate', 'filter_date', array(
                'apply_filter' => ApplyFilters::getDateFilterFunction(),
            ));
                
            $builder->add('lastChangeDate', 'filter_date', array(
                'apply_filter' => ApplyFilters::getDateFilterFunction(),
            ));
            
            $builder->add('submit-filter', 'submit');
        }
    
        public function getName() {
            return 'order_index_view_filter';
        }
    
        public function setDefaultOptions(OptionsResolverInterface $resolver) {
            $resolver->setDefaults(array(
                'data_class' => 'FMS\System\MainBundle\Entity\Order',
                'csrf_protection'   => false,
                'validation_groups' => array('filtering'), // avoid NotBlank() constraint-related message
                'method' => 'GET',
            ));
        }
    }

Then i have the OrderCustomerFilterType:

    <?php
    namespace FMS\System\MainBundle\Filter;
    
    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\FormBuilderInterface;
    use FMS\System\MainBundle\Filter\OrderCustomerAddressFilterType;
    use Doctrine\ORM\QueryBuilder;
    use Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderExecuterInterface;
    use Doctrine\ORM\Query\Expr;
    use Symfony\Component\OptionsResolver\OptionsResolverInterface;
    use Lexik\Bundle\FormFilterBundle\Filter\Form\Type\EmbeddedFilterTypeInterface;
    use FMS\System\MainBundle\Filter\ApplyFilters;
    
    class OrderCustomerFilterType extends AbstractType// implements EmbeddedFilterTypeInterface
    {
        public function buildForm(FormBuilderInterface $builder, array $options) {
           $builder->add('customerNumber', 'filter_number'
                   //,array('apply_filter' => ApplyFilters::getAddressNameFilterFunction())
            );
           $builder->add('Address', new OrderCustomerAddressFilterType(), array(
                'add_shared' => OrderCustomerAddressFilterType::getAddShared()
                )
            );
        }
    
        public function getName() {
            return 'order_customer_filter';
        }
        
        public function getParent() {
            return 'filter_sharedable'; //this allow us to use the "add_shared" option
        }
        
        public function setDefaultOptions(OptionsResolverInterface $resolver) {
            $resolver->setDefaults(array(
                'data_class' => 'FMS\System\MainBundle\Entity\Customer',
                'csrf_protection'   => false,
                'validation_groups' => array('filtering'), // avoid NotBlank() constraint-related message
                'method' => 'GET',
            ));
        }
        
        /**
         * This method aims to add all joins you need
         */
        public static function getAddShared() {
        
            return function (FilterBuilderExecuterInterface $qbe) {
                $closure = function(QueryBuilder $filterBuilder, $alias, $joinAlias, Expr $expr) {
                    // add the join clause to the doctrine query builder
                    // the where clause for the fields will be added automatically with the right alias later by the Lexik\Filter\QueryBuilderUpdater
                    $filterBuilder->leftJoin($alias . '.Customer', 'c');
                };
    
                // then use the query builder executor to define the join, the join's alias and things to do on the doctrine query builder.
                $qbe->addOnce($qbe->getAlias().'.Customer', 'c', $closure);
            };
        }
    }

And the OrderCustomerAddressFilterType

    <?php
    namespace FMS\System\MainBundle\Filter;
    
    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Doctrine\ORM\QueryBuilder;
    use FMS\System\MainBundle\Filter\ApplyFilters;
    use Lexik\Bundle\FormFilterBundle\Filter\FilterOperands;
    use Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderExecuterInterface;
    use Doctrine\ORM\Query\Expr;
    use Symfony\Component\OptionsResolver\OptionsResolverInterface;
    use Lexik\Bundle\FormFilterBundle\Filter\Form\Type\EmbeddedFilterTypeInterface;
    
    class OrderCustomerAddressFilterType extends AbstractType// implements EmbeddedFilterTypeInterface
    {
        public function buildForm(FormBuilderInterface $builder, array $options) {
           
            
            $builder->add('firstname', 'filter_text', array(
                //'apply_filter' => ApplyFilters::getAddressNameFilterFunction('order_customer_address_firstname'),
                'condition_pattern' => FilterOperands::STRING_BOTH,
           ));
            
           //$builder->add('lastname', 'filter_text');
        }
    
        public function getName() {
            return 'order_customer_address_filter';
        }
        
        public function getParent() {
            return 'filter_sharedable'; //this allow us to use the "add_shared" option
        }
        
        public function setDefaultOptions(OptionsResolverInterface $resolver) {
            $resolver->setDefaults(array(
                'data_class' => 'FMS\System\MainBundle\Entity\Address',
                'csrf_protection'   => false,
                'validation_groups' => array('filtering'), // avoid NotBlank() constraint-related message
                'method' => 'GET',
            ));
        }
        
        /**
         * This method aims to add all joins you need
         */
        public static function getAddShared() {
            
            return function (FilterBuilderExecuterInterface $qbe) {
                $closure = function(QueryBuilder $filterBuilder, $alias, $joinAlias, Expr $expr) {
                    // add the join clause to the doctrine query builder
                    // the where clause for the fields will be added automatically with the right alias later by the Lexik\Filter\QueryBuilderUpdater
                    $filterBuilder->leftJoin($alias . '.Address', 'add');
                };
    
                // then use the query builder executor to define the join, the join's alias and things to do on the doctrine query builder.
                $qbe->addOnce($qbe->getAlias().'.Address', 'add', $closure);
            };
        }
    }

The Filter for the Customer attribute customerNumber works properly but if i enter a Order.Customer.Address.firstname i receive this error:

    Can't set condition object for: "Customer.Address.firstname" 
    in vendor/lexik/form-filter-bundle/Lexik/Bundle/FormFilterBundle/Filter/Condition/ConditionBuilder.php at line 43

This is my root Condition Node:

    object(Lexik\Bundle\FormFilterBundle\Filter\Condition\ConditionNode)[1424]
      private 'operator' => string 'and' (length=3)
      private 'parent' => null
      private 'children' => 
        array (size=1)
          0 => 
            object(Lexik\Bundle\FormFilterBundle\Filter\Condition\ConditionNode)[1425]
              private 'operator' => string 'and' (length=3)
              private 'parent' => 
                &object(Lexik\Bundle\FormFilterBundle\Filter\Condition\ConditionNode)[1424]
              private 'children' => 
                array (size=1)
                  0 => 
                    object(Lexik\Bundle\FormFilterBundle\Filter\Condition\ConditionNode)[1426]
                      private 'operator' => string 'and' (length=3)
                      private 'parent' => 
                        &object(Lexik\Bundle\FormFilterBundle\Filter\Condition\ConditionNode)[1425]
                      private 'children' => 
                        array (size=0)
                          empty
                      private 'fields' => 
                        array (size=1)
                          'Address.firstname' => null
              private 'fields' => 
                array (size=1)
                  'Customer.customerNumber' => null
      private 'fields' => 
        array (size=6)
          'status' => null
          'invoiceId' => null
          'sales' => null
          'createDate' => null
          'lastChangeDate' => null
          'submit-filter' => null

**Comment by cedric-g** [comment]
Hi, can you have a try with the `fix_159` branch ?

**Comment by Timo-Linde** [comment]
tried and approved = ) thank you very much.

**Comment by cedric-g** [comment]
Thx, I've merged it into `master`.
