### ISSUE TITLE
Remove deprecated

### ISSUE THREAD

**Issue by garak** [lexik/LexikFormFilterBundle#164]
The way for handle options changed since Symfony 2.5, where ``setDefaultOptions`` has been deprecated in favour of ``configureOptions``.
To make this bundle work with future Symfony 2.8, every occurrence of old method should be change with the new one.
Please notice that such change will also change the requirements of this bundle, that is currently for Symfony ~2.3 (need to be restricted to Symfony ~2.5).
I can submit a PR, if you agree.

**Comment by Rvanlaak** [comment]
+1 on also setting the translation domain to `null` for `filter_entity` so it will not translate those.

**Comment by cedric-g** [comment]
Ok for a PR =)

**Comment by garak** [comment]
I have to warn you that such PR will high requirements of this bundle to Symfony 2.7

**Comment by Rvanlaak** [comment]
2.7 would be nice, as it is the new LTS version! Also see https://github.com/lexik/LexikFormFilterBundle/pull/147#issuecomment-105793288

**Comment by cedric-g** [comment]
My first idea was to wait a bit before to bump requirements to 2.7, but maybe it's useless to wait, so let's go for SF 2.7 as minimum version.

**Comment by garak** [comment]
I think that 2.7 is more or less suitable to use now, being at 2.7.1 (likely with 2.7.2 going out soon).
Of course, this would require to release a new tag (maybe a major one?), keeping old tags back-compatible with ~2.3.

**Comment by cedric-g** [comment]
Yes if the requirements change to SF 2.7 I will create a `4.0.0` tag.

**Comment by Rvanlaak** [comment]
And a new branch for `2.3` as well? So bugfixes can be ported to that version.

**Comment by kick-the-bucket** [comment]
It's really easy to make the types compatible with all Symfony versions (both below and above 2.7):
leave the `setDefaultOptions` methods, but move the logic to `configureOptions` method and call it from `setDefaultOptions`, since (for the time being, till Symfony3 comes out) parameter types are compatible, just not the same.

**Comment by Rvanlaak** [comment]
Why leave an empty `setDefaultOptions`? Don't see why you should do that.

**Comment by kick-the-bucket** [comment]
Don't leave it empty - make a call to `configureOptions` in `setDefaultOptions`. That way both methods point to the new one and all Symfony versions are supported.

**Comment by Rvanlaak** [comment]
That's already handled via the BC

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/AbstractType.php#L43-L62

**Comment by kick-the-bucket** [comment]
This only means that the current code will work as is with the newer (>=2.7) Symfony versions. If the methods are only renamed, compatibility with older (<2.7) versions will be broken.
