### ISSUE TITLE
Problem with filter_date_range

### ISSUE THREAD

**Issue by yblancof2** [lexik/LexikFormFilterBundle#166]
I am writing to clarify some doubts about the bundle LexikFormFilterBundle. This bundle is wonderful and can do several things but sometimes not clear to its operation. Would like to know how I can make use of provider types filter_date_range. When used with the following error No value found for key "left_date" in form data. Please help me fix it. Thanks in advance

**Comment by cedric-g** [comment]
Hi, can you provide a sample code to see how you use the `filter_date_range` ? and what version of the bundle are you using ?

**Comment by yblancof2** [comment]
Cedric good morning , first of all thanks for answering . As I said in the previous post on this wonderful bundle . My problem is the next: 
I want to use the component in an input datapicker but when using this the bundle not work for me because the corresponding text field must be single_text and component does not. I wonder how you could use this component Jquery . Also wanted to know how to send the data by the method POST to not display as long url . I await your reply and thanks in advance 



-- 
"A veces pretendo ser normal, pero me aburro y vuelvo a ser yo." 
Ing. Yaniel Blanco Fernández 
Universidad de las Ciencias Informáticas

**Comment by Rvanlaak** [comment]
If you want to use a single datepicker to select a range, you should set the corresponding form fields with javascript after the user completed the selection. Please see http://jqueryui.com/datepicker/#date-range

**Comment by yblancof2** [comment]
Thanks for answering Rvanlaak I used the datepicker component. The problem is to integrate it with the bundle, this does not work gives me the error "No value found for key "left_date" in form data". Greetings.

**Comment by Rvanlaak** [comment]
That means you haven't set any value yet, you can use the `onchange` event in jQuery to copy the appropriate value from the datepicker to the form fields that are output by Symfony. 

Or you can bind the datepicker to the two date fields, as you can see in the code snippet by clicking "view source" on the link I've sent earlier.

**Comment by yblancof2** [comment]
Sorry I do not understand. Could you give a piece of code which exemplifies this tells me. Greetings and thanks in advance

**Comment by Rvanlaak** [comment]
Copy/paste:

```html
<script>
  $(function() {
    $( "#from" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 3,
      onClose: function( selectedDate ) {
        $( "#to" ).datepicker( "option", "minDate", selectedDate );
      }
    });
    $( "#to" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 3,
      onClose: function( selectedDate ) {
        $( "#from" ).datepicker( "option", "maxDate", selectedDate );
      }
    });
  });
  </script>
 
<label for="from">From</label>
<input type="text" id="from" name="from">
<label for="to">to</label>
<input type="text" id="to" name="to">
```
Where the `from` and `to` input could match the `filter_date_range` fields.

**Comment by yblancof2** [comment]
Thank you for your help. I'll try to do it and I will tell the result. Thanks again

**Comment by yblancof2** [comment]
Write again for the same problem, I did not work with the jquery date range picker. As I have seen when the request is sent to the controller in the url will parameters such as:
"sn[fecha][left_date][day]=1&sn[fecha][left_date][month]=1&sn[fecha][left_date][year]=2012&sn[fecha][right_date][day]=2&sn[fecha][right_date][month]=3&sn[fecha][right_date][year]=2012".
This is simpre and when not using the widget form attr => single_text. But this attr is necessary if you want to use the datepicker. Enclosed is my code if anyone can help me. greetings

->add('fecha', 'filter_date_range', array(
                    'left_date_options' => array(
                        'label' => 'Fecha incial',
                        'attr' => array(
                            'class' => 'form-control',
                            'placeholder' => 'Fecha inicial'),
                        'empty_value' => array('year' => 'Año', 'month' => 'Mes', 'day' => 'Dia'),
                        'format' => 'ddMMyyyy'
                    ),
                    'right_date_options' => array(
                        'label' => 'Fecha final',
                        'attr' => array(
                            'class' => 'form-control',
                            'placeholder' => 'Fecha final'),
                        'empty_value' => array('year' => 'Año', 'month' => 'Mes', 'day' => 'Dia'),
                        'format' => 'ddMMyyyy'
                    ),
                    'label' => 'Collect Period'
                ))


![screenshot-localhost 2015-07-16 14-21-44](https://cloud.githubusercontent.com/assets/11427255/8731545/15ddbf42-2bc6-11e5-9d45-ab2699fce372.png)

**Comment by Rvanlaak** [comment]
I don't understand your problem? What is going wrong exactly?

**Comment by cedric-g** [comment]
I'm not sure to undertand your problem too, but did you try to use the `widget` option.

```php
'left_date_options' => array(
    // ...
    'format' => 'ddMMyyyy',
    'widget' => 'single_text'
),
```

**Comment by david303** [comment]
Im having a similiar issue.

If I submit the filter form to the same action it was created in, then everythings fine.
But if I send It to a different action and try and recreate it using the request data then I get

error 500 "No value found for key "left_date" in form data."

This code works:

    public function listOrdersAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $form = $this->get('form.factory')->create(new OrderFilterType());
        if ($request->query->has($form->getName())) {

            $form->submit($request->query->get($form->getName()));

            $filterBuilder = $this->get('doctrine.orm.entity_manager')
                ->getRepository('PepperLeafWebBundle:SubscriptionOrder')
                ->createQueryBuilder('s');

            $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($form, $filterBuilder);

            $query = $filterBuilder->getQuery();
    ...

This code fails on addFilterConditions(), the exact same data is in $formData :
    public function exportOrderCsvAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $form = $this->get('form.factory')->create(new OrderFilterType());
        $formData = $request->query->get($form->getName());
        //dump($formData);

        $filterBuilder = $this->get('doctrine.orm.entity_manager')
            ->getRepository('PepperLeafWebBundle:SubscriptionOrder')
            ->createQueryBuilder('s');

        $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($form, $filterBuilder);
        $query = $filterBuilder->getQuery();

    ...

If I remove the filter_date_range field from the form type, then everything is ok but I need it.
