### ISSUE TITLE
Could not load type "filter_text", "by default the required option is set to false for all filter_xxx types.". Where to change this option ?

### ISSUE THREAD

**Issue by sruj** [lexik/LexikFormFilterBundle#168]
from docs (3. Provided form types): "Notes: by default the required option is set to false for all filter_xxx types."

Where to change this option ?

**Comment by Rvanlaak** [comment]
http://symfony.com/doc/current/reference/forms/types/form.html#required

**Comment by sruj** [comment]
so i mixed two issues having nothing in common. Required option is not a problem.

Problem is error: Could not load type "filter_text" while doing https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/working-with-the-bundle.md#i-simple-example and http://ahcobos.com/content/form-filters-symfony2-complete-example

**Comment by cedric-g** [comment]
Hi, if you can't load the `filter_text` type maybe you should check the bundle is correctly loaded.
