### ISSUE TITLE
Documentation on user custom filters

### ISSUE THREAD

**Issue by Bendells** [lexik/LexikFormFilterBundle#169]
Hello,

I didn't know much where to go through to get the information, so I hope I am not going through the wrong channel. 

I am looking to have a front-end filter form that the user can customize depending on its need. I just don't seem to find the proper documentation on how to apply that with Lexik. 

I guess I would need to build a PostSubmit and a PreSet event and send my data to the controller, but how would I go about changing the behavior of Lexik(default AND) dynamically?

**Comment by cedric-g** [comment]
Hi, so yes you can use the `PRE_SET_DATA` event to dynamically add some fields to your form. But using the events won't be convient to manage the condition builder instance (this object is used to define operators between fields).

So maybe you can build your form by using the `form.factory` service:

```php
$formBuilder = $container->get('form.factory')->createBuilder();

$conditionBuilder = new \Lexik\Bundle\FormFilterBundle\Filter\Condition\ConditionBuilder();
$rootNode = $conditionBuilder->root('AND');

if (...) {
    $formBuilder->add('field_A', 'filter_text');
    $rootNode->field('field_A');
}

if (...) {
    $formBuilder->add('field_B', 'filter_number');
    $rootNode->field('field_B');
}

$formBuilder->setAttribute('filter_condition_builder', $conditionBuilder);

$form = $formBuilder->getForm();
```
Once you get your form object you can use the `lexik_form_filter.query_builder_updater` service. The example above will result as `field_A AND field_B`, so if you need a more complex AND/OR combination you will have to add some child nodes to the condition root node.

**Comment by Bendells** [comment]
Ok thanks Cédric,

I'll give it a try
