### ISSUE TITLE
LexikFormFilterBundle and MongoDB

### ISSUE THREAD

**Issue by jiguillen** [lexik/LexikFormFilterBundle#170]
Could I use this bundle with MongoDB?

Thanks!

**Comment by Rvanlaak** [comment]
Bundle has `doctrine/orm` as a dependency instead of `doctrine/odm` so the answer is no :wink:

**Comment by jiguillen** [comment]
Thank you, do you know a similar bundle for working with MongoDB. This bundle was just what I was looking for.
