### ISSUE TITLE
Modifying bundle to work with Mongodb-ODM

### ISSUE THREAD

**Issue by jiguillen** [lexik/LexikFormFilterBundle#171]
Could I modify bundle to work with Mongodb-ODM?

If that is possible, what I should change?

Thanks!

**Comment by cedric-g** [comment]
Hi, yes it's possible to make the bundle work with Doctrine Mongodb ODM but it will require to create 3 classes:
* a query class similar to `Lexik\Bundle\FormFilterBundle\Filter\Doctrine\ORMQuery`. This class help the `lexik_form_filter.query_builder_updater` service to know the part of the event name corresponding to the storage (orm, dbal, ...). See `QueryInterface::getEventPartName()`.
* a subscriber class to listen all filter events like `Lexik\Bundle\FormFilterBundle\Event\Subscriber\DoctrineORMSubscriber`. This class aim to build condition expression for each filter type (expression are passed to the condition builder).
* a MongoDBApplyFilterListener similar to `Lexik\Bundle\FormFilterBundle\Event\Listener\DoctrineApplyFilterListener`. This class is used to build the final condition by using expression from the condition builder.

**Comment by jiguillen** [comment]
Thank you very much, that has been very usefull for me. But I am having a problem with MongoDBApplyFilterListener, DoctrineApplyFilterListener uses Doctrine\ORM\Query\Expr\Composite and Doctrine\DBAL\Query\Expression\CompositeExpression. I've looking for something similar in ODM, and I can't find it, so I can´t use methods add and count.

Do you know how can I solve it? 

Perhaps it is something easy, but I'm starting with Symfony and Mongo. 

Thanks, regards!!!

**Comment by cedric-g** [comment]
I havn't use mongodb for months, so maybe I'm not correct, but you can try to use the `addAnd` and `addOr` methods form the query builder and expression class.
In the following class I removed the $parameters property that should be useless with mongo.

```php
namespace Lexik\Bundle\FormFilterBundle\Event\Listener;

use Doctrine\MongoDB\Query\Builder;
use Doctrine\MongoDB\Query\Expr;
use Lexik\Bundle\FormFilterBundle\Event\ApplyFilterConditionEvent;
use Lexik\Bundle\FormFilterBundle\Filter\Condition\ConditionInterface;
use Lexik\Bundle\FormFilterBundle\Filter\Condition\ConditionNodeInterface;

class DoctrineMongoDBApplyFilterListener
{
    private $whereMethod;

    /**
     * @param string $whereMethod
     */
    public function __construct($whereMethod)
    {
        $whereMethod = strtolower($whereMethod);

        $this->whereMethod = (null === $whereMethod || 'and' === $whereMethod) ? 'addAnd' : 'addOr';
    }

    /**
     * @param ApplyFilterConditionEvent $event
     */
    public function onApplyFilterCondition(ApplyFilterConditionEvent $event)
    {
        $qb = $event->getQueryBuilder();
        $conditionBuilder = $event->getConditionBuilder();

        $this->parameters = array();
        $expression = $this->computeExpression($qb, $conditionBuilder->getRoot());

        if (null !== $expression) {
            $qb->{$this->whereMethod}($expression);
        }
    }

    /**
     * @param Builder                $queryBuilder
     * @param ConditionNodeInterface $node
     * @return Expr
     */
    protected function computeExpression(Builder $queryBuilder, ConditionNodeInterface $node)
    {
        if (count($node->getFields()) == 0 && count($node->getChildren()) == 0) {
            return null;
        }

        $method = ($node->getOperator() == ConditionNodeInterface::EXPR_AND) ? 'addAnd' : 'addOr';

        $expression = $queryBuilder->expr(); // create a new expression object
        $expressionsCount = 0;

        foreach ($node->getFields() as $condition) {
            if (null !== $condition) {
                /** @var ConditionInterface $condition */
                $expression->{$method}($condition->getExpression());
                $expressionsCount++;
            }
        }

        foreach ($node->getChildren() as $child) {
            $subExpr = $this->computeExpression($queryBuilder, $child);

            if (null !== $subExpr) {
                $expression->{$method}($subExpr);
                $expressionsCount++;
            }
        }

        return ($expressionsCount > 0) ? $expression : null;
    }
}
```

**Comment by jiguillen** [comment]
I'm not getting that it works. I've created the 3 classes and I've added in listeners.xml:

&#60;parameter key="lexik_form_filter.get_filter.doctrine_odm.class">Lexik\Bundle\FormFilterBundle\Event\Subscriber\DoctrineODMSubscriber&#60;/parameter>
&#60;parameter key="lexik_form_filter.apply_filter.doctrine_odm.class">Lexik\Bundle\FormFilterBundle\Event\Listener\DoctrineMongoDBApplyFilterListener&#60;/parameter>

&#60;service id="lexik_form_filter.get_filter.doctrine_odm" class="%lexik_form_filter.get_filter.doctrine_odm.class%">
            &#60;tag name="kernel.event_subscriber" />
&#60;/service>

&#60;service id="lexik_form_filter.apply_filter.doctrine_odm" class="%lexik_form_filter.apply_filter.doctrine_odm.class%">
            &#60;argument>%lexik_form_filter.where_method%&#60;/argument>
            &#60;tag name="kernel.event_listener" event="lexik_filter.apply_filters.odm" method="onApplyFilterCondition" />
        &#60;/service>

When I run the app, it fails in FilterBuilderUpdater::addFilterConditions because $event->getFilterQuery() is null, I think may be the listener, because it isn't executing the method DoctrineMongoDBApplyFilterListener::onApplyFilterCondition.

Any idea?

I am sorry all my questions, I am beginner.

Thanks for all.

**Comment by cedric-g** [comment]
If the `$event->getFilterQuery()` return `null` maybe check you set the query object on the event in https://github.com/lexik/LexikFormFilterBundle/blob/master/Event/Listener/PrepareListener.php#L60

**Comment by jiguillen** [comment]
It was just that! Thanks!

I think it is almost working, now I'am having a problem with ExpressionBuilder::stringLike, this method uses the method Doctrine\ORM\Query\Expr::like which doesn´t exist in ODM.

I've been looking for a similar method in ODM, but I can't found it.

**Comment by cedric-g** [comment]
hum maybe you can try:
```php
$qb->field($field)->equals('/' . $value . '/');
```
or
```php
$qb->field($field)->equals(new \MongoRegex('/.*' . $value . '.*/i'));
```

**Comment by jiguillen** [comment]
Finally, I  I haven't been able to do it works. Maybe, I'll try it when I learn more about Mongo.

Thank you for all!!!

**Comment by cedric-g** [comment]
I've created a `mongodb` branch, if you wa

**Comment by cedric-g** [comment]
I've created a `mongodb` branch, if you want to try you will have to enable listeners for mongo in the config:
```yml
# app/config/config.yml
lexik_form_filter:
    listeners:
        doctrine_mongodb: true
        doctrine_orm: true
        doctrine_dbal: true
```

**Comment by senj-gold** [comment]
Unrecognized option "listeners" under "lexik_form_filter"

**Comment by senj-gold** [comment]
Hi. You are planning to add branches Mongo release version? or merge from branch master

**Comment by Rvanlaak** [comment]
Think that branch isn't stable yet, so if you could test it and add some PRs that would be awesome.

**Comment by senj-gold** [comment]
ok

**Comment by cedric-g** [comment]
I've tested the branch only with simple filters and embedded documents, not with relations defined by using references.

**Comment by RagishaP** [comment]
Use lexikjwt and Use this link .https://github.com/m0uj/symfony4-mongodb-jwt-starter
It is really helpful .
check the security.yaml file configurations  and the User document
if possible use mongodb provider as below:
our_db_provider:
            mongodb:
                class: App\Document\ERPUserMaster
                property: username
