### ISSUE TITLE
Can't add a validation on a filter

### ISSUE THREAD

**Issue by nicosomb** [lexik/LexikFormFilterBundle#174]
Hello, 

Thank you for LexikFormFilterBundle. 

I have a field `entry.domainName` and I added a filter on it. 
I want to prevent filtering when user types a domainName with a length < 3. 
Here is my buildForm: 

```
        $builder
            ->add('domainName', 'filter_text', array(
                'condition_pattern' => FilterOperands::STRING_BOTH,
                'apply_filter' => function (QueryInterface $filterQuery, $field, $values)
                    {
                        $value = $values['value'];
                        if (strlen($value) <= 3 || empty($value)) {
                            return null;
                        }

                        // $expr = $filterQuery->getExpr();
                        //
                        // $paramName = $field;
                        //
                        // return $filterQuery->createCondition(
                        //     $expr->eq($field, ':'.$paramName),
                        //     array($paramName => $values['value'])
                        // );

                        return $filterQuery->getQueryBuilder()->add('where', 'e.domainName = :e_domainName')->setParameter(':e_domainName', $values['value']);
                    }
            ));
```

My entry has "symfony.com" in its domainName field.

If I type "sy" for the domainName, no filter: OK. 
If I type "symfony" for the domainName, filter: no result, OK.
If I type "symfony.com", filter, but KO: 

> An exception has been thrown during the rendering of a template ("Too many parameters: the query defines 1 parameters and you bound 2") in AcmeBundle:Entry:entries.html.twig at line 36.

Here is my line 36: `{% for entry in entries %}` 

Regards, 

Nicolas

**Comment by cedric-g** [comment]
Hi, which version of the bundle are you using ?

**Comment by nicosomb** [comment]
`"lexik/form-filter-bundle": "~4.0"`

**Comment by cedric-g** [comment]
Ok, and do you get the same error by using `$filterQuery->createCondition()` ?

**Comment by nicosomb** [comment]
It works. Now, how can I do to create a "%term%" query? (like `FilterOperands::STRING_BOTH` parameter).

**Comment by nicosomb** [comment]
Ah maybe `ExpressionBuilder::stringLike` can be useful!

**Comment by cedric-g** [comment]
Yes or by using the doctrine expression class: http://doctrine-orm.readthedocs.org/en/latest/reference/query-builder.html#the-expr-class

> // Example - $qb->expr()->like('u.firstname', $qb->expr()->literal('Gui%'))
> public function like($x, $y); // Returns Expr\Comparison instance

**Comment by nicosomb** [comment]
Thank you so much :+1:
