### ISSUE TITLE
Any way to easily display applied filters on my page?

### ISSUE THREAD

**Issue by nicosomb** [lexik/LexikFormFilterBundle#175]
Here is how we implemtend your bundle: 

![](https://lut.im/E6xxa3YL/2ZCt2Osb)

But when we click on filter button, the sidebar is hidden. 
And I want to display on the main page, near to "There are 3 entries": "with **domain name** and **creation date** filters" or something like that. 

My question: is there any way to easily get in twig template the applied filters?

**Comment by antoinearrive** [comment]
J'ai aussi besoin d'une réponse, j'ai la même problèmatique
