### ISSUE TITLE
Bug in doc code

### ISSUE THREAD

**Issue by Xigi** [lexik/LexikFormFilterBundle#182]
I found a small bug in the code in the documentation under https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/working-with-the-bundle.md#iv-filter-customization

The bit 
```
    $expression = $filterQuery->getExpr()->eq($field, ':'.$paramName);
```
Should be
```
    $expression = $filterQuery->getQueryBuilder()->expr()->eq($field, ':'.$paramName);
```
If I'm not mistaken.
I hope I'm posting it to the right place, thanks for the great bundle anyways

**Comment by Rvanlaak** [comment]
`ORMQuery` actually has a shortcut method, so both are valid:

https://github.com/lexik/LexikFormFilterBundle/blob/master/Filter/Doctrine/ORMQuery.php#L64-L72

**Comment by Xigi** [comment]
I'm sorry, my mistake

**Comment by Rvanlaak** [comment]
:+1:
