### ISSUE TITLE
filter_choice OPERATOR_LOWER_THAN_EQUAL

### ISSUE THREAD

**Issue by xmon** [lexik/LexikFormFilterBundle#186]
It is the first time I use this bundle in a project with Symfony2, to create a search filter in the front end.

I need to create a field with the filter **filter_choice** and use: 
`'condition_operator' => FilterOperands::OPERATOR_LOWER_THAN_EQUAL`
own filter **filter_number**.

I am reviewing the documentation and questions of developers, but I can not give the key to do so.

I appreciate any point to fix it.

thank you

**Comment by cedric-g** [comment]
Hi, the `condition_operator` option is specific to the `filter_number` type, you can't use it with the `filter_choice`.

**Comment by xmon** [comment]
Thank you @cedric-g,

Any idea to make it with filter_choice?

thanks again

**Comment by cedric-g** [comment]
I think the best is to create a custom type based on a choice type.
