### ISSUE TITLE
FilterTypeExtension->getExtendedType() triggers deprecated warning in Symfony 2.8

### ISSUE THREAD

**Issue by spackmat** [lexik/LexikFormFilterBundle#187]
Hi,

I am refactoring my app to be compatible with Symfony 2.8/3.0. The LexikFormFilterBundle triggers one deprecation message in my app, because `FilterTypeExtension->getExtendedType()` returns the string 'form' instead of `Symfony\Component\Form\Extension\Core\Type\FormType::class`. I did a quick fix for myself by changing this and the corresponding service-definition in the form.xml to:

        
        <service id="lexik_form_filter.type_extension.filter_extension" class="%lexik_form_filter.type_extension.filter_extension.class%">
            <tag name="form.type_extension" extended_type="Symfony\Component\Form\Extension\Core\Type\FormType" />
        </service>

Now the message hast past away. Maybe the bundle should do this, too (or a variant of this, which maintains compatibility with older Symfony versions).

Edit: Oh, now I get several other warning due to deprecated use of `getParent()` and `getName()` definitions inside the filter type classes.

**Comment by rvanlaak** [comment]
Don't think the bundle will bump the minimum requirement to the new LTS version 2.8 yet, so maybe a new branch could fix this.

**Comment by spackmat** [comment]
You are right, I opened a new branch and filed a pull request with my changes. I don't see deprecated warning anymore in my app, but didn't run the tests (because I had unmet requirements with MongoDB on my dev machine).

**Comment by rvanlaak** [comment]
Yes, see https://github.com/lexik/LexikFormFilterBundle/pull/185
