### ISSUE TITLE
Symfony 3.0 compatibility ?

### ISSUE THREAD

**Issue by gazouweb** [lexik/LexikFormFilterBundle#190]
Hello,
When the bundle will be compatible with Symfony 3.0?
Thank you

**Comment by rvanlaak** [comment]
see https://github.com/lexik/LexikFormFilterBundle/pull/188 and https://github.com/lexik/LexikFormFilterBundle/pull/185 before opening new issue :+1:

**Comment by gazouweb** [comment]
Sorry, I just saw after posting.
