### ISSUE TITLE
Upgrade guide from 3.0 to 4.0

### ISSUE THREAD

**Issue by Jean85** [lexik/LexikFormFilterBundle#191]
I'm using an old version of the bundle and I would like to upgrade. I found really useful guides for previous versions, but I can't see anything for 4.0...

Can someone provide it? What are the BC issues?

**Comment by cedric-g** [comment]
Hi, the difference between 3.0.x and 4.0.x is I changed the minimum SF verion from 2.3 to 2.7 but there are no big changes in the bundle so you should not get any BC.

**Comment by Jean85** [comment]
Great, thanks!
