### ISSUE TITLE
Request for more documentation how to use your Bundle

### ISSUE THREAD

**Issue by jeroendesloovere** [lexik/LexikFormFilterBundle#195]
I'm relatively new to Symfony and would love to see some more documentation how to use your Bundle.
F.e.: how to filter Vehicles by "Manufacturer" or "Model", ...

**Comment by rvanlaak** [comment]
I think all documentation you'll need for this bundle can be found in `Resources/doc`

Take a look at https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/index.md

**Comment by raymon2683** [comment]
I think a more detailed documentation for starter would be welcomed! Because , for us new to Symfony2 it's a difficult to get this to work with the documentation provided.

**Comment by rvanlaak** [comment]
There are quite some examples in the docs, did you get those working? One thing I could imagine is that Symfony forms and Doctrine entities aren't documented, but providing documentation about these is outside of the scope of this bundle. They are the basics of this bundle though.
