### ISSUE TITLE
empty_value in BooleanFilterType triggers deprecated warning in Symfony 2.8

### ISSUE THREAD

**Issue by spackmat** [lexik/LexikFormFilterBundle#196]
Hi,

In my last pull request (for the Symfony 2.8/3.0 compatibility), I forgot to remove the `empty_value` option in the `BooleanFilterType`, but this still gives me deprecated warning in Symfony 2.8. So this should be changed to `placeholder` instead.

Greets,
spackmat

**Comment by j0k3r** [comment]
Well, you can submit a PR then :smile:
