### ISSUE TITLE
knp paginator

### ISSUE THREAD

**Issue by boonkerz** [lexik/LexikFormFilterBundle#198]
does anyone have an working example with the paginator bundle?

i can search but when i change the page the filter is lost.

**Comment by rvanlaak** [comment]
Make sure the GET-parameters are added to the paginator link. According to my implementation it seems the filters are passed properly by default.

As long as this isn't an issue with the bundle think the best place to ask this is at StackOverflow. Over there way more people that will see your question. Please also provide code samples.

**Comment by boonkerz** [comment]
hi i think my code is correct or?

```php
        $qb = $userRepository->createQueryBuilder('product')
            ->andWhere('product.shop = :shop_id')
            ->andWhere("product.uuid != ''")
            ->setParameter("shop_id", $selectedShop->getUid())
            ->orderBy('product.uid', 'ASC');

        $form = $this->createForm(SearchType::class);
        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            $qb = $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($form, $qb);
        }
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $qb,
            $request->query->getInt('page', 1),
            15
        );
```

**Comment by rvanlaak** [comment]
Don't know, does it work for you? What's the problem?

**Comment by boonkerz** [comment]
the filter is applied but the pagination does not include the filter params only ?page=2

**Comment by boonkerz** [comment]
Issue found the search form method must be GET.

POST do not work
