### ISSUE TITLE
filter_number_range needs 'condition_operator' if you use 'data' option on 'left_number_options' or 'right_number_options'

### ISSUE THREAD

**Issue by Kharestani** [lexik/LexikFormFilterBundle#200]
Hi
Thanks for the awesome bundle!
I find a little problem that I think might be a bug. basically when filter_number_range used in the formType class with the preset data we need to set the data to both  'left_number_options' and 'right_number_options' to make it work but it doesn't unless ```'condition_operator' => FilterOperands::OPERATOR_GREATER_THAN  ```mentioned in the options as well. I might be wrong and it might be how you designed it originally but It might be good if you mention that in the doc as well.
anyway thanks alot for your time and effort.
It's how it works now:
```php
  ->add('price', 'filter_number_range', array(
	'left_number_options' => array(
                 'data' => 0, 
                 'condition_operator' => FilterOperands::OPERATOR_GREATER_THAN
         ),
	'right_number_options' => array(
                 'data' => 2000, 
                 'condition_operator' => FilterOperands::OPERATOR_LOWER_THAN)
	))
```
The Error at submitting is like this:
> Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice:  Undefined index: condition_operator" at C:\ ... \vendor\lexik\form-filter-bundle\Event\Subscriber\AbstractDoctrineSubscriber.php line 180

**Comment by cedric-g** [comment]
Hi, as you defined the `left_number_options` it override the default value defined in the form type, so yes you have to set the `condition_operator` option to make it work. But maybe I can set a fallback value in case the `condition_operator` is not defined, it would allow users to set it only if they want to change the default operator.

**Comment by Kharestani** [comment]
That's a very good Idea
Thanks
