### ISSUE TITLE
Could not load type "filter_text" 

### ISSUE THREAD

**Issue by thomas2411** [lexik/LexikFormFilterBundle#201]
On Symfony 2.8, PHP 5.6.10, on both 5.0.0 and dev-master version I get this error.

I have configured bundle like in docs in config.yml for doctrine. I see in debug:container that all services are loaded. I create form like this:
```
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'filter_text');
    }
```

```
    protected function createFilterForm($filterData)
    {
        return $this->get('form.factory')->create(new ArticleFilterType(), $filterData, array(
            'action' => $this->generateUrl(sprintf('%s', $this->routePrefix)),
            'method' => 'GET',
            'attr'   => array('class' => 'form-inline')
        ));
    }
```
And I get this error. Any idea what is going on? For filter_entity I get:

```
The type name specified for the service "lexik_form_filter.type.filter_entity" does not match the actual name. Expected "filter_entity", given "Lexik\Bundle\FormFilterBundle\Filter\Form\Type\EntityFilterType" 
```

**Comment by rvanlaak** [comment]
What about using the FQCN as `EntityFilterType::class`? That's the recommended way of adding filter fields on `dev-master`.

Next to that I don't see any code that does add the entity filter. Do you also have this on a stable tag of this library?

**Comment by thomas2411** [comment]
Indeed, this is the solution. Docs are for older version (4 I guess). 

When use this, it works, thank you.
```
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
         ->add('username', TextFilterType::class);
}
```
The some for ```EntityFilterType::class```
