### ISSUE TITLE
using form with symfony 3

### ISSUE THREAD

**Issue by mreichstadt** [lexik/LexikFormFilterBundle#203]
Hi,
I'm currently trying to use your bundle with a simple entity, in my Symfony 3 project.

Here are my informations:
- entity: INRA\FormationBundle\Entity\Conducteur.php
    with an attribute called nom
- filter: INRA\FormationBundle\Filter\ConducteurFilterType.php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('nom', 'filter_text');
    }
- controller: INRA\FormationBundle\Controller\ConducteurController.php
    with ConducteurFilterType in use

When in my indexAction I try to create the form with that command:
$form = $this->get('form.factory')->create(new ConducteurFilterType());

I get the following error:
Expected argument of type "string", "INRA\FormationBundle\Filter\ConducteurFilterType" given

Do you know what I did wrong?
thank you very much

**Comment by spike31** [comment]
Hi,

You need to use `ConducteurFilterType::class` and not new ConducteurFilterType() in SF3.

**Comment by mreichstadt** [comment]
Hi thank you very much, it works now.
regards

2016-02-12 9:40 GMT+01:00 Gilles Gauthier <notifications@github.com>:
