### ISSUE TITLE
Could not load type "TextFilterType" 

### ISSUE THREAD

**Issue by lil-works** [lexik/LexikFormFilterBundle#208]
I'm running in symfony3 and installed "lexik/form-filter-bundle": "dev-master"

Whene I use  
`$builder->add('username', TextFilterType::class);`

I get this error
`Could not load type "AppBundle\Filter\TextFilterType" `

Any suggestion?

**Comment by rvanlaak** [comment]
You forgot the use statement on `TextFilterType`

**Comment by lil-works** [comment]
Oh my god thanks and sorry

**Comment by rvanlaak** [comment]
No problem, think StackOverflow is the best place to go for such issues. You can help us to discuss new features and library bugs over here ;)
