### ISSUE TITLE
apply_filter not working on entity associations

### ISSUE THREAD

**Issue by joshcrawmer4** [lexik/LexikFormFilterBundle#210]
the apply_filter closure never gets called with entity associations and embeddeding filters. Is this normal. Seems like a bug to me. It gets called on other filter Types. Let me know what you need from me and please help!

**Comment by joshcrawmer4** [comment]
Nevermind everyone, Make sure to add the apply_filter to the associated form type. Everything works great. Could you add this to the docs?

**Comment by rvanlaak** [comment]
What should be added to the docs? `apply_filter` works fine right? Think the docs about that already are quite extensive :+1:  https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/index.md
