### ISSUE TITLE
Date range filter errors not rendered in twig

### ISSUE THREAD

**Issue by webdevilopers** [lexik/LexikFormFilterBundle#217]
Field Type:
```php
                $form
                    ->add('date', 'filter_date_range', array(
                        'left_date_options' => array(
                            'attr' => array('class' => 'datepicker'),
                            'widget' => 'single_text',
                            'format' => 'dd.MM.y',
                        ),
                        'right_date_options' => array(
                            'attr' => array('class' => 'datepicker'),
                            'widget' => 'single_text',
                            'data' => new \DateTime('now'),
                            'format' => 'dd.MM.y',
                        ),
                        'required' => true
                    ));
```

Assert on `data_class`:
```php
    /**
     * @var array $date
     * @Assert\Collection(
     *     fields = {
     *      "left_date" = {
     *          @Assert\NotNull(),
     *          @Assert\DateTime()
     *      },
     *      "right_date" = {
     *          @Assert\NotNull(),
     *          @Assert\DateTime()
     *      }
     *  }
     * )
     */
    public $date = [];
```

TWIG:
```twig
{{ form_row(inspection_results_filter_form.date) }}
```

When leaving the `right_date` blank the validator works fine and adds the error to the Profiler toolbar.
Unfortunately the error doesn't render inside the template.

Any idea?

**Comment by rvanlaak** [comment]
What about actually rendering the error?

```
{{ form_errors(inspection_results_filter_form.date) }}
```

Think StackOverflow is the right place for things like this, given this isn't a bug with the bundle right? They will be able to help you way faster over there.

**Comment by webdevilopers** [comment]
I think we misunderstood @rvanlaak !

Currently I use the `form_row` helper on all filter fields. This helper does include the `form_errors` helper!
The `filter_entity` shows the errors while `date_range_filter` does not.

I added an Assert to a `filter_entity` field. The profiler correctly shows:
![filter_errors](https://cloud.githubusercontent.com/assets/3479626/16154530/9a4dc8e6-34ab-11e6-83ae-93a080ec6e28.png)

But the template only shows:
![twig_filter_errors](https://cloud.githubusercontent.com/assets/3479626/16154548/b00e35f8-34ab-11e6-81ed-8ff6ba19029f.png)

Is this the expected behaviour? Does the `filter_date_range` not automatically render the error messages?

**Comment by webdevilopers** [comment]
But both filter types use the default behaviour. Why do they behave differently?

**Comment by cedric-g** [comment]
@webdevilopers maybe just override the default [filter_date_range_widget](https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/views/Form/form_div_layout.html.twig#L30-L34) block and add a call to ``form_errors(form.xxxxx_date)`` inside.

**Comment by webdevilopers** [comment]
Sure @cedric-g , there should be enough workarounds though. ;)
Just wanted to ensure this is an issue and report it. :)
