### ISSUE TITLE
TextFilterType default condition_pattern

### ISSUE THREAD

**Issue by phjedi** [lexik/LexikFormFilterBundle#225]
Hi. In docs written:

> condition_pattern: this option allows you to configure the way you to filter the string. The default pattern is FilterOperands::STRING_STARTS

It's "3. Provided types".

But in [code](https://github.com/lexik/LexikFormFilterBundle/blob/master/Filter/Form/Type/TextFilterType.php#L43):

`'condition_pattern'      => FilterOperands::STRING_EQUALS,`

**Comment by DemonTPx** [comment]
This has been changed (and fixed) in 5.0.2. It is now configurable:

    lexik_form_filter:
        condition_pattern: text.equals # or text.starts or whatever... defaults to text.starts
