### ISSUE TITLE
The option "type" does not exist.

### ISSUE THREAD

**Issue by vkgroupes** [lexik/LexikFormFilterBundle#241]
Hello,
I have got an error "The option "type" does not exist"  trying to add Collection Filter type
```php
$builder->add('bookingline', Filters\CollectionAdapterFilterType::class, array(
            'type'       => BookingLineFilterType::class,
            'add_shared' => function (FilterBuilderExecuterInterface $qbe)  {
                $closure = function (QueryBuilder $filterBuilder, $alias, $joinAlias, Expr $expr) {
                    // add the join clause to the doctrine query builder
                    // the where clause for the label and color fields will be added automatically with the right alias later by the Lexik\Filter\QueryBuilderUpdater
                    $filterBuilder->leftJoin($alias . '.bookingline', $joinAlias);
                },
                // then use the query builder executor to define the join and its alias.
                $qbe->addOnce($qbe->getAlias().'.bookingline', 'opt', $closure);
            },
        ));
```

The option "type" does not exist. Defined options are: "action", "add_shared", "allow_extra_fields", "apply_filter", "attr", "auto_initialize", "block_name", "by_reference", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "data_extraction_method", "default_data", "disabled", "empty_data", "entry_options", "entry_type", "error_bubbling", "error_mapping", "extra_fields_message", "filter_condition_builder", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "mapped", "method", "post_max_size_message", "property_path", "required", "translation_domain", "trim", "upload_max_size_message", "validation_groups".

I'm new in symfony. Really don't know should I do to solve it.
Thanks in advance.

**Comment by cedric-g** [comment]
Hi, use `entry_type` instead of `type`.

**Comment by vkgroupes** [comment]
Thank you!
