### ISSUE TITLE
DoctrineORMSubscriber depends on id field naming convention

### ISSUE THREAD

**Issue by canaaerus** [lexik/LexikFormFilterBundle#250]
The id field in an `Entity` of mine is called `entity_id` instead of just `id` and can be accessed through `getEntityId`. Unfortunately this makes `DoctrineORMSubscriber::getValueIdentifier` fail, saying

> Can't call method "getId()" on an instance of "AppBundle\Entity\Entity"

The symfony `EntityType` field uses `Symfony\Bridge\Doctrine\Form\ChoiceList\IdReader` to get the id from an entity. Maybe that can be used here to? I think it would work, at least for single-column-ids (which is all you support now anyway, if i read the code correctly).

Another thought I had, was to subclass `DoctrineORMSubscriber`, add my own naming convention to `getValueIdentifier` and change `lexik_form_filter.get_filter.doctrine_orm.class` to this new class. Only first `getValueIdentifier` would have to be `protected` instead of `private`. Also it seems like that parameter (`….getfilter.…`) is not overridable⁉

**Comment by cedric-g** [comment]
Hi :) can you check with the branch `fix_250` ? If it's ok I will merge it.

**Comment by canaaerus** [comment]
Yes, that works nicely. Thank you a lot :+1:
