### ISSUE TITLE
Issues with the titles of the doc articles

### ISSUE THREAD

**Issue by javiereguiluz** [lexik/LexikFormFilterBundle#252]
As you can see in any of the Markdown files of the doc (example --> https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/installation.md) the main page title doesn't render nicely.

The problem is that the title is rendered as a list element:

```
1. Installation
===============
```

The same happens if you do:

```
1) Installation
===============
```

The solution is to remove the `1.` or add something before the `1.`. Example:

```
Chapter 1. Installation
=======================
```

**Comment by cedric-g** [comment]
Hi, it's nice again now :smiley:

**Comment by javiereguiluz** [comment]
Thanks!
