### ISSUE TITLE
Example needed . How to add filter field which covers a joined field.

### ISSUE THREAD

**Issue by rileyrg** [lexik/LexikFormFilterBundle#257]
In the docs here it discusses using set parts to tell the queryUpdater about the joins in the case that the underlying QueryBuilder has joins (Im not sure why it cant read that itself from the QB but maybe it's simply not possibly).  My base query is:

```
        $queryBuilder = $this->createQueryBuilder("p")
            ->leftJoin("p.eyeColor", "e")
            ->leftJoin("p.adressData", "a")
            ->leftJoin("p.adminAdressData", "aa")
            ->orderBy("p.surname", "DESC");

```
So my equivalent setParts call to mirror the doc example is:

```
 // set the joins
            $qb_updater->setParts(array(
                '__root__' => 'p',
                'p.adressData' => 'a',
                'p.adminAdressData' => 'aa',
                'p.eyeColor'      => 'e'
            ));
```

Now I want to simply add a filter field which will filter against Person.AdressData.city or in this case  "a.city". Since "city" is unique I thought that I might just :

`
->add('city', Filters\TextFilterType::class);

`
But it doesnt work. Neither does "a.city". I have really been googling and reading and am missing the wood for the trees. An example and explanation would be much appreciated.

**Comment by cedric-g** [comment]
If you pre-set you joins that just means you won't have to define them by using the `FilterBuilderExecuterInterface`.

Wihtout pre-set joins:
```php
$builder->add('item', new ItemFilterType(), array(
    'add_shared' => function (FilterBuilderExecuterInterface $qbe) {
        $closure = function (QueryBuilder $filterBuilder, $alias, $joinAlias, Expr $expr) {
            $filterBuilder->leftJoin($alias . '.item', $joinAlias);
        };

        $qbe->addOnce($qbe->getAlias().'.item', 'i', $closure);
    }
));
```
And if you pre-set the joins, you can leav the closue empty:
```php
$builder->add('item', new ItemFilterType(), array(
    'add_shared' => function (FilterBuilderExecuterInterface $qbe) {}
));
```
But you still have to build your form type as the same way according to your relations. The bundle can't guess the text city field is the city property from the adressData relation.

**Comment by rileyrg** [comment]
OK I have that. Thanks.

**Comment by enjoi11** [comment]
Hi there,

I have exact the same problem as @rileyrg but your solution @cedric-g doesn't work for me. I always get "the option "add_shared" does not exist." thus I added `    public function getParent()
    {
        return Filters\SharedableFilterType::class; // this allow us to use the "add_shared" option
    }` I'm on Symfony 3.3.
