### ISSUE TITLE
DateFilterType : no option for operands?

### ISSUE THREAD

**Issue by rileyrg** [lexik/LexikFormFilterBundle#258]
Having just discovered the nice 'condition_pattern' option for TextFilterType it strikes me that DateFilterType could benefit from this ability too. Possible or am I missing something?  Now I could create a user get to return an age (in this case) and filter on conditions on a number but it might also be nice to say "date of birth after 1 jan 1966" for example-

**Comment by cedric-g** [comment]
This feature is not implemented for the DateFilterType . Maybe you can use a DateRangeFilterType, and fill only one of the date fileds.
