### ISSUE TITLE
Allow use of "property_path" option on forms ?

### ISSUE THREAD

**Issue by jorismulliez** [lexik/LexikFormFilterBundle#269]
Hi,

I'm using this bundle a lot, and it works fine !
But I ended up with very long urls...

> ?Ftf[event][0]=24&Ftf[firstname]=&Ftf[created][left_date][day]=&Ftf[created][left_date][month]=&Ftf[created][left_date][year]=&Ftf[created][right_date][day]=&Ftf[created][right_date][month]=&Ftf[created][right_date][year]=&Ftf[status]=&Ftf[f]=&t=1500232427.7373

I want to shorten them, I have already reduced the form name ("Ftf" here).
Now I want to reduce each field name.

I read that symfony can have a different "attribute name" than the property name by using the property : "property_path".

So for the simple example here : https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/basics.md#i-simple-example
Can you just allow to change : 
```php
$builder->add('name', Filters\TextFilterType::class);
```
by
```php
$builder->add('n', Filters\TextFilterType::class, ['property_path' => 'name']);
```

I tried on my project, the form is well rendered, but if I submit it, I have an error : 

> Cannot write property "title" to an array. Maybe you should write the property path as "[title]" instead?

Thanks a lot,

**Comment by NorthBlue333** [comment]
Hi,
This is still the case. Is there a reaon why this issue is closed?
