### ISSUE TITLE
Symfony 3.4 and autowiring FilterBuilderUpdaterInterface

### ISSUE THREAD

**Issue by spackmat** [lexik/LexikFormFilterBundle#280]
Hi,

until Symfony 3.3, I injected the `FilterBuilderUpdaterInterface` via autowiring into my controllers instead of getting the service from the container as documented:

    $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($filterForm, $qb);

This doesn't work anymore with Symfony 3.4, where I get `null` injected instead of the service.

Question is: is there any other way to inject the `FilterBuilderUpdater` service into my controllers via autowiring? My workaround for now is using the documented way via the container.

**Comment by nckenn** [comment]
Any update on this?

**Comment by rvanlaak** [comment]
This has to do with Symfony's autowiring defaults. Don't think it's the bundle that did change the service to return `null`. Do you have multiple classes that override the default implementation of `FilterBuilderUpdaterInterface`?

You can try to autowire the implementing class instead of the interface, or play around with `_instanceof` a bit: https://symfony.com/doc/current/service_container/3.3-di-changes.html#auto-configure-with-instanceof

**Comment by spackmat** [comment]
Hi @rvanlaak there is no custom implementation of FilterBuilderUpdaterInterface and within my vendor, there is only the Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdater implementing it.

When I try to inject Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdater or Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdaterInterface into my controller action, I get the following error message:

> Controller "App\Controller\MyController::indexAction()" requires that you provide a value for the "$filterBuilderUpdater" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.

Until Symfony 3.3, injecting Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdaterInterface worked fine.

As a workaround, I define my own alias for the service in my services.yaml:

    # fixes a BC break in Symfony 3.4, open ticket: https://github.com/lexik/LexikFormFilterBundle/issues/280
    Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdater: '@lexik_form_filter.query_builder_updater'

There was a similar problem with the KnpMenuBundle, which was solved there by defining such an alias, see https://github.com/KnpLabs/KnpMenuBundle/pull/385

**Comment by rvanlaak** [comment]
Thanks for referring the `KnpMenuBundle` ticket. It would be great if you'd be able to to create a PR with that same alias solution.

**Comment by spackmat** [comment]
Okay, I aliased FilterBuilderUpdaterInterface and FilterBuilderUpdater to lexik_form_filter.query_builder_updater.
