### ISSUE TITLE
LexikFormFilterBundle and Symfony 4.2

### ISSUE THREAD

**Issue by aSalehTibi** [lexik/LexikFormFilterBundle#306]
Hi all,
i am new to Symfony and i am trying to use LexikFormFilterBundle with Symfony 4.2.
first, is the LexikFormFilterBundle works with 4.2 if yes what should i name the config file in config folder ? 
thx for ur help

**Comment by pbowyer** [comment]
Yes it works with 4.2 (I am using `dev-master`). I haven't set up any config so can't confirm, but I would try adding to the `config/packages/framework.yaml` file.

**Comment by aSalehTibi** [comment]
Hi 
ok thx for the answer
 i have one more question :D  how can i get the Filterd results  if i reach to dql qurey. in the example 
wirten only that they dump the query, NOW how  can i get the results of that dql query 
thx again for ur help
