### ISSUE TITLE
v5.0.9 Broken with symfony 3.4

### ISSUE THREAD

**Issue by zghosts** [lexik/LexikFormFilterBundle#312]
commit 66c196d6eb596efc98dd42c474afa169486adab1 renames getExtendedType to getExtendedTypes in order to fix deprecation notices with symfony 4.2, however getExtendedType is still very much part of the Symfony\Component\Form\FormTypeExtensionInterface, so the extension now violates the interface and no longer works with symfony 4.1 and below

**Comment by jbator** [comment]
My Sf 3.4 apps using this bundle are broken after last update :(

Error: Class Lexik\Bundle\FormFilterBundle\Filter\Form\FilterTypeExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Form\FormTypeExtensionInterface::getExtendedType)

**Comment by spike31** [comment]
5.0.10 is available ☺️
