### ISSUE TITLE
Service "lexik_form_filter.query_builder_updater" not found

### ISSUE THREAD

**Issue by mreichstadt** [lexik/LexikFormFilterBundle#315]
Hi,
I've got this problem and I don't know how to fix it.
I've installed the bundle under sf4.2. In my index, I set the following code:

$filters = $docInterneRepository->getAll();
        if ($request->query->has($form->getName()))
        {
           $form->submit($request->query->get($form->getName()));
           $this->get('lexik_form_filter.query_builder_updater')->addFilterConditions($form, $filters);
        }
My filter uses GET method. 

I've already had a look at others issues that may look like mine, but I didn't find any solutions.
Can somebody help me please?
regards

**Comment by mreichstadt** [comment]
I obtain this error:

Service "lexik_form_filter.query_builder_updater" not found: even though it exists in the app's container, the container inside "App\Controller\DocInterneController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session" and "twig" services. Try using dependency injection instead.

**Comment by lbr-linux** [comment]
> You should inject the FilterBuilderUpdaterInterface interface into the controller function
> 
> File xxController.php
> 
> use Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdaterInterface;
> 
> ....
> 
> public function indexAction(Request $request, FilterBuilderUpdaterInterface $query_builder_updater) {
> ...
> $form = $this->get('form.factory')->create('NameFormType');
> $filters = $docInterneRepository->getAll();
> if ($request->query->has($form->getName())) {
> $form->submit($request->query->get($form->getName()));
> $query_builder_updater->addFilterConditions($form, $filters);
> }
> ...
> }

This not working in Symfony 5.1, Is this bundle still under maintenance?

**Comment by spike31** [comment]
See #331  or #332 
Nothing change
