### ISSUE TITLE
Works in symfony 5.1 ?

### ISSUE THREAD

**Issue by lbr-linux** [lexik/LexikFormFilterBundle#331]
I try but i have this error:

Cannot autowire argument $query_builder_updater of "App\Controller\TestController::indexAction()": it references interface "Lexik\Bundle\FormFilterBundle\Filter\FilterBuilderUpdaterInterface" but no such service exists. Did you create a class that implements this interface?

**Comment by spike31** [comment]
Hi,

The v6 tags works with SF 5.1, tests passes and I use the bundle on differents projects on SF5.1

Just inject `FilterBuilderUpdaterInterface $filterBuilderUpdater`for example where you want
