### ISSUE TITLE
doctrine/orm to specific

### ISSUE THREAD

**Issue by peternijssen** [lexik/LexikFormFilterBundle#351]
Hi,

I am unable to install V7.0.0 as I have a requirement on doctrine/orm 2.10.3 in my composer file, while 7.0.0 requires 2.10.0

Current requirement in V7.0.0:
```
"doctrine/orm": "2.10"
```

I believe it should be:
```
"doctrine/orm": "^2.10"
```

**Comment by spike31** [comment]
@peternijssen hi,
You right, thx! 

Just release tag
