### ISSUE TITLE
Filtering on many-to-many relationships

### ISSUE THREAD

**Issue by rvanlaak** [lexik/LexikFormFilterBundle#40]
I've got a many-to-many relationship between User and Group and I want to filter on the group in the user list. The 'filter_entity' works great, because it shows a list of all available groups:

```
->add('groups', 'filter_entity', array(
     'class'    =>  'CompanyAppBundle:User\Group',
))
```

But, submitting the filterform results in a semantical error:

```
[Semantical Error] line 0, col 59 near 'groups = 2': Error: Invalid PathExpression. 
StateFieldPathExpression or SingleValuedAssociationField expected.
```

Is it possible to add a check in the library to test on the type of relationship?

**Comment by djoo** [comment]
Hi, thanks for this. This is a version with one value (multiple = false)

```php
$builder->add('myEntity', 'filter_entity', array(
            'class'         => 'AppMyBundle:MyEntity',
            'expanded'      => false,
            'multiple'      => false,
            'apply_filter'  => function (QueryInterface $filterQuery, $field, $values)
            {
                $query = $filterQuery->getQueryBuilder();
                $query->leftJoin($field, 't');
                $value = $values['value'];
                if (isset($value)){
                $query->andWhere($query->expr()->in('t.id', $value->getId()));
                }
            }));
```

**Comment by franciscomemoli** [comment]
I did exactly the same but didn't work to me. The problem was that the andWhere don't add the filter at the query, so I did this:


$builder->add('myEntity', 'filter_entity', array(
            'class'         => 'AppMyBundle:MyEntity',
            'expanded'      => false,
            'multiple'      => false,
            'apply_filter'  => function (QueryInterface $filterQuery, $field, $values)
            {
                $query = $filterQuery->getQueryBuilder();
                $query->innerJoin($field, 't');
                $value = $values['value'];
                if (isset($value)){
                    $paramName = sprintf('p_%t', str_replace('.', '_', $field));
                    $expression = $filterQuery->getExpr()->eq("t.id", ':'.$paramName);
                    $parameters = array($paramName => $values['value']->getId()); 
                    return $filterQuery->createCondition($expression, $parameters);
                }
            }));
I changed to innerJoin because I want to filter with and and if you use left join it will no work properly.

**Comment by cedric-g** [comment]
@franciscomemoli I think you and @djoo are just not using the same version of the bundle. The `$filterQuery->createCondition(...)` is only available since the version `3.x`.

**Comment by jinxboy13** [comment]
Hi
I'm going Bazoook!!!!
please help!
also i'm new at this so ....
```php
->add('color', 'filter_entity', array(
	'class' => 'TehranCodeShopsBundle:Color',
	'multiple' => true,
))
->add('categories', 'filter_entity', array(
	'class'         => 'TehranCodeShopsBundle:Category',
	'expanded'      => false,
	'multiple'      => true,
	'apply_filter'  => function (QueryInterface $filterQuery, $field, $values)
		{
			$query = $filterQuery->getQueryBuilder();
			$query->Join($field, 'm');

			// Filter results using orWhere matching ID
			foreach ($values['value'] as $value)
			{
				$query->orWhere($query->expr()->in('m.id', $value->getId()));
			}
		},
))
->add('sizes', 'filter_entity', array(
	'class'         => 'TehranCodeShopsBundle:Size',
	'expanded'      => false,
	'multiple'      => true,
	'apply_filter'  => function (QueryInterface $filterQuery, $field, $values)
		{
			$query = $filterQuery->getQueryBuilder();
			$query->Join($field, 's');

			// Filter results using orWhere matching ID
			foreach ($values['value'] as $value)
			{
				$query->orWhere($query->expr()->in('s.id', $value->getId()));
			}
		},
))
->add('price', 'filter_number_range');
```
The product has a Many to Many relation with `categories` and `sizes` so I used `apply_filter` in both places but when I submit the filter it goes `OR` between `categories` and `sizes` instead of `AND`!
I also tried using `filter_condition_builder` to solve it but no success.
Thank you in advance!
